---
# Source: tilde-user/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tilde
  labels:
    app.kubernetes.io/name: tilde
    helm.sh/chart: tilde-user-0.1.0
    app.kubernetes.io/instance: tilde
    app.kubernetes.io/managed-by: Tiller
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 22
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    app.kubernetes.io/name: tilde
    app.kubernetes.io/instance: tilde

---
# Source: tilde-user/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tilde
  labels:
    app.kubernetes.io/name: tilde
    helm.sh/chart: tilde-user-0.1.0
    app.kubernetes.io/instance: tilde
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tilde
      app.kubernetes.io/instance: tilde
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tilde
        app.kubernetes.io/instance: tilde
    spec:
      securityContext:
        fsGroup: 101
      containers:
        - name: tilde-user-ssh
          image: "tilde/ssh:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: TILDE_USER
              value: paulczar
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
          volumeMounts:
            - mountPath: /home/user/public_html
              name: public-html
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
            
        - name: tilde-user-http
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: public-html
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
            
      volumes:
        - name: public-html
          emptyDir: {}

